"""Provider-independent agent SDK built on LiteLLM.

Every name below is what the README's examples import -- keep this list in
sync with the README rather than the other way around.
"""

from __future__ import annotations

from .agent import LiteAgentClient, LiteAgentOptions, query
from .compaction import (
    AllOf,
    AnyOf,
    Cascade,
    CompactionContext,
    CompactionError,
    CompactionOptions,
    CompactionResult,
    CompactionStrategy,
    CompactionTrigger,
    ContextBudgetExceeded,
    PruneToolResults,
    RecentTokens,
    Summarize,
    TokenCounter,
    TokenCountRequest,
    TokenEstimate,
    TokenThreshold,
    TriggerContext,
    TurnThreshold,
    all_of,
    any_of,
    cascade,
    heuristic_tokens,
)
from .compaction.background import BackgroundMemoryOptions, MemorySnapshot
from .fusion import FusionOptions
from .history import apply_compaction
from .pr_risk_agent import PRRiskAgent, PullRequest, RiskAssessment
from .routers import JevAgent, JevModelRouter, JevTier, ModelRouter, StaticRouter
from .tools import Tool
from .types import (
    AgentEvent,
    AssistantMessage,
    BatchUpdate,
    CompactionCompleted,
    CompactionEvent,
    CompactionFailed,
    CompactionReason,
    CompactionSkipped,
    CompactionStarted,
    CompactionUpdate,
    ContentBlock,
    HistoryEdit,
    Message,
    ReplacePrefix,
    ReplaceToolResult,
    SummaryMessage,
    TextBlock,
    TextDelta,
    ToolResultBlock,
    ToolUseBlock,
    TurnContext,
    UserMessage,
)
from .usage import TokenUsage

__all__ = [
    "AgentEvent",
    "AllOf",
    "AnyOf",
    "AssistantMessage",
    "BackgroundMemoryOptions",
    "BatchUpdate",
    "Cascade",
    "CompactionCompleted",
    "CompactionContext",
    "CompactionError",
    "CompactionEvent",
    "CompactionFailed",
    "CompactionOptions",
    "CompactionReason",
    "CompactionResult",
    "CompactionSkipped",
    "CompactionStarted",
    "CompactionStrategy",
    "CompactionTrigger",
    "CompactionUpdate",
    "ContentBlock",
    "ContextBudgetExceeded",
    "FusionOptions",
    "HistoryEdit",
    "JevAgent",
    "JevModelRouter",
    "JevTier",
    "LiteAgentClient",
    "LiteAgentOptions",
    "MemorySnapshot",
    "Message",
    "ModelRouter",
    "PRRiskAgent",
    "PruneToolResults",
    "PullRequest",
    "RecentTokens",
    "ReplacePrefix",
    "ReplaceToolResult",
    "RiskAssessment",
    "StaticRouter",
    "Summarize",
    "SummaryMessage",
    "TextBlock",
    "TextDelta",
    "TokenCountRequest",
    "TokenCounter",
    "TokenEstimate",
    "TokenThreshold",
    "TokenUsage",
    "Tool",
    "ToolResultBlock",
    "ToolUseBlock",
    "TriggerContext",
    "TurnContext",
    "TurnThreshold",
    "UserMessage",
    "all_of",
    "any_of",
    "apply_compaction",
    "cascade",
    "heuristic_tokens",
    "query",
]
